### ISSUE TITLE
Asyncio Bug in `chats` options

### ISSUE THREAD

**Issue by tominovoj** [ail-project/ail-feeder-discord#25]
Hello, 

each time after command `python3 bin/feeder.py chats` I am getting following error:

```
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f880ff073a0>
transport: <_SelectorSocketTransport closing fd=7>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I think it can be [connected with](https://stackoverflow.com/questions/45600579/asyncio-event-loop-is-closed-when-getting-loop) following bug..

**Comment by Terrtia** [comment]
Hey @tominovoj !

Have you already joined a server?
Do you also experience the same issue with the other commands?
